((c-ts-mode . ((eval . (flycheck-mode -1))
               (eval . (lsp-mode -1))
               (eval . (apheleia-mode -1))
               (eval . (etags-regen-mode t))
               (eval . (xref-etags-mode t))
                     )))
